/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.JLabel;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author agniv
 */
public class ViewAppointmentsGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewAppointmentsGUI.class.getName());

    /**
     * Creates new form ViewAppointmentsGUI
     */
    public ViewAppointmentsGUI() {
        initComponents();
        loadTable();
        setLocationRelativeTo(null);
    }
    private void loadTable() {
    try {
        Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/hospital","root","1234"
        );

        String query = "SELECT a.appointment_id, p.name AS patient, d.name AS doctor, a.date, a.time " +
                       "FROM appointments a " +
                       "JOIN patients p ON a.patient_id = p.patient_id " +
                       "JOIN doctors d ON a.doctor_id = d.doctor_id";

        PreparedStatement pst = con.prepareStatement(query);
        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        while(rs.next()){
            model.addRow(new Object[]{
                rs.getInt("appointment_id"),
                rs.getString("patient"),
                rs.getString("doctor"),
                rs.getString("date"),
                rs.getString("time")
            });
        }

        con.close();

    } catch(Exception e){
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Appointment Records");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Appintment ID", "Patient", "Doctor", "Date", "Time"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setText("Delete");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setText("Update");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel1)
                .addContainerGap(187, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();

if(row == -1){
    JOptionPane.showMessageDialog(this, "Select a row first");
    return;
}

int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());

int confirm = JOptionPane.showConfirmDialog(this, "Are you sure?");
if(confirm != 0) return;

try {
    Connection con = DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/hospital","root","1234"
    );

    String query = "DELETE FROM appointments WHERE appointment_id=?";
    PreparedStatement pst = con.prepareStatement(query);

    pst.setInt(1, id);

    pst.executeUpdate();

    JOptionPane.showMessageDialog(this, "Deleted successfully");

    loadTable();

    con.close();

} catch(Exception e){
    e.printStackTrace();
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();

if(row == -1){
    JOptionPane.showMessageDialog(this, "Select a row first");
    return;
}

int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());

try {
    Connection con = DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/hospital","root","1234"
    );

    // create components
    JComboBox<String> patientBox = new JComboBox<>();
    JComboBox<String> doctorBox = new JComboBox<>();
    JTextField dateField = new JTextField();
    JTextField timeField = new JTextField();

    // load patients
    PreparedStatement pst1 = con.prepareStatement("SELECT * FROM patients");
    ResultSet rs1 = pst1.executeQuery();
    while(rs1.next()){
        patientBox.addItem(rs1.getInt("patient_id") + " - " + rs1.getString("name"));
    }

    // load doctors
    PreparedStatement pst2 = con.prepareStatement("SELECT * FROM doctors");
    ResultSet rs2 = pst2.executeQuery();
    while(rs2.next()){
        doctorBox.addItem(rs2.getInt("doctor_id") + " - " + rs2.getString("name"));
    }

    // popup panel
    JPanel panel = new JPanel(new GridLayout(4,2));
    panel.add(new JLabel("Patient"));
    panel.add(patientBox);
    panel.add(new JLabel("Doctor"));
    panel.add(doctorBox);
    panel.add(new JLabel("Date"));
    panel.add(dateField);
    panel.add(new JLabel("Time"));
    panel.add(timeField);

    int result = JOptionPane.showConfirmDialog(this, panel, "Update Appointment", JOptionPane.OK_CANCEL_OPTION);

    if(result != JOptionPane.OK_OPTION) return;

    // get values
    int patientId = Integer.parseInt(patientBox.getSelectedItem().toString().split(" - ")[0]);
    int doctorId = Integer.parseInt(doctorBox.getSelectedItem().toString().split(" - ")[0]);

    String date = dateField.getText().trim();
    String time = timeField.getText().trim();

    // validation
    try {
        java.sql.Date.valueOf(date);
        java.sql.Time.valueOf(time);
    } catch(Exception e){
        JOptionPane.showMessageDialog(this, "Invalid date/time format");
        return;
    }

    // update query
    String query = "UPDATE appointments SET patient_id=?, doctor_id=?, date=?, time=? WHERE appointment_id=?";
    PreparedStatement pst = con.prepareStatement(query);

    pst.setInt(1, patientId);
    pst.setInt(2, doctorId);
    pst.setString(3, date);
    pst.setString(4, time);
    pst.setInt(5, id);

    pst.executeUpdate();

    JOptionPane.showMessageDialog(this, "Updated successfully");

    loadTable();

    con.close();

} catch(Exception e){
    e.printStackTrace();
}
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewAppointmentsGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
