/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author agniv
 */
public class ViewRecordsGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewRecordsGUI.class.getName());

    /**
     * Creates new form ViewRecordsGUI
     */
    public ViewRecordsGUI() {
        initComponents();
        loadTable();
                setLocationRelativeTo(null); // center window
    }
    public void loadTable() {
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/hospital","root","1234"
        );

        String query = "SELECT * FROM patients";
        PreparedStatement pst = con.prepareStatement(query);
        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        while(rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("patient_id"),
                rs.getString("name"),
                rs.getInt("age"),
                rs.getString("gender"),
                rs.getString("disease")
            });
        }
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);  // ID
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(150); // Name
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(50);  // Age
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(100); // Gender
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(120); // Disease
        con.close();
    } catch(Exception e) {
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Patient Records");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Age", "Gender", "Disease"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setText("Delete");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setText("Update");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
int row = jTable1.getSelectedRow();

if(row == -1){
    JOptionPane.showMessageDialog(this, "Select a row first");
    return;
}

int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());

int confirm = JOptionPane.showConfirmDialog(this, "Are you sure?");
if(confirm != 0) return;

try {
    Connection con = DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/hospital","root","1234"
    );

    // 🔍 check if patient has appointments
    String checkQuery = "SELECT * FROM appointments WHERE patient_id=?";
    PreparedStatement checkStmt = con.prepareStatement(checkQuery);
    checkStmt.setInt(1, id);

    ResultSet rs = checkStmt.executeQuery();

    if(rs.next()){
        JOptionPane.showMessageDialog(this, "Cannot delete. Patient has appointments.");
        con.close();
        return;
    }

    // ✅ safe to delete
    String query = "DELETE FROM patients WHERE patient_id=?";
    PreparedStatement pst = con.prepareStatement(query);
    pst.setInt(1, id);

    pst.executeUpdate();

    JOptionPane.showMessageDialog(this, "Deleted successfully");

    loadTable();

    con.close();

} catch(Exception e){
    e.printStackTrace();
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // disabled
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();

if(row == -1){
    JOptionPane.showMessageDialog(this, "Select a row first");
    return;
}

int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());

String currentName = jTable1.getValueAt(row, 1).toString();
String currentAge = jTable1.getValueAt(row, 2).toString();
String currentGender = jTable1.getValueAt(row, 3).toString();
String currentDisease = jTable1.getValueAt(row, 4).toString();

// take input from user
String name = JOptionPane.showInputDialog(this, "Enter Name:", currentName);
String ageStr = JOptionPane.showInputDialog(this, "Enter Age:", currentAge);
String gender = JOptionPane.showInputDialog(this, "Enter Gender:", currentGender);
String disease = JOptionPane.showInputDialog(this, "Enter Disease:", currentDisease);

if(name == null || ageStr == null || gender == null || disease == null) return;

int confirm = JOptionPane.showConfirmDialog(this, "Update this record?");
if(confirm != 0) return;

try {
    Connection con = DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/hospital","root","1234"
    );

    String query = "UPDATE patients SET name=?, age=?, gender=?, disease=? WHERE patient_id=?";
    PreparedStatement pst = con.prepareStatement(query);

    pst.setString(1, name.trim());
    pst.setInt(2, Integer.parseInt(ageStr.trim()));
    pst.setString(3, gender.trim());
    pst.setString(4, disease.trim());
    pst.setInt(5, id);

    pst.executeUpdate();

    JOptionPane.showMessageDialog(this, "Updated successfully");

    loadTable();

    con.close();

} catch(Exception e){
    e.printStackTrace();
}
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewRecordsGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
